### ISSUE TITLE
Setup the repo and tasks so CUSP students can hit the ground running

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/LA-LocalGeo-CrossWalk#1]
@vr00n I populated the readme based on your cool NYC example. Key immediate task IMHO is to inventory and align on the administrative geographies we want to inventory for this Winter Sprint. 

Can also prioritize as LA is very complicated and some will be a real pain in the you-know-what.

Note after this is all done this could make a nice blog post comparing / contrasting the LA and NYC municipal administrative architectures :)

**Comment by vr00n** [comment]
Thanks @patwater . I will update the repo with Issue.md templates and review this project to ensure it complies with dirt simple spec as specified in 
https://github.com/argo-marketplace/test-project

Will close this out when completed.

**Comment by patwater** [comment]
Cool @vr00n seeing a kickoff meeting and stub issue.md file. Any other issues? Looking to get those spec-ed out so students can hit the ground running

**Comment by vr00n** [comment]
@patwater when are the actual dates when students are available?

**Comment by patwater** [comment]
Winter break will run from 12/22 to 1/23.
