### ISSUE TITLE
Create an API

### ISSUE THREAD

**Issue by lingyielia** [argo-marketplace/LA-LocalGeo-CrossWalk#10]
A "stretch" goal for this project. 

Create an API to access the LA cross walk file.  

- Option 1: Use Carto.com
   - Upload our final CSV file to Carto and export it as API.

- Option 2: Use [dirt simple postgis http api](https://github.com/tobinbradley/dirt-simple-postgis-http-api)
   - Host using AWS

**Comment by vr00n** [comment]
@lingyielia FYI i updated the above for clarity.

**Comment by gauravcusp** [comment]
I used the [result](https://drive.google.com/open?id=1W-fXFVE4afhv26R_GSmod-XU4AsJdtm5) file and [converted](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/api.ipynb) it to [json file](https://s3.amazonaws.com/argodata/dummy.json) . After that i created a local json-server to host the api and run it on Postman GUI. 
![image](https://user-images.githubusercontent.com/31963299/34902478-223b2bba-f7ea-11e7-9a02-2c79e1cd872f.png)

I've hosted the file on AWS  as well but working on api file for that.

@vr00n  We will have slightly more clarity on API after your AWS session i believe. Until then can you let us know if this what was required.

**Comment by vr00n** [comment]
Fantastic work @gauravcusp !

**Comment by gauravcusp** [comment]
@vr00n 
I attempted to work with Python and Flask to create and API and host data on local server. I managed to get the data on server but since the data is enormous, its really slow. I've placed the files [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/tree/master/API) along with README to re-create the steps. Also, this is the result I got from API:
(Please disregard the first block as I intend to remove it, but the file size is making it difficult to edit)
![image](https://user-images.githubusercontent.com/31963299/35174891-0a381dde-fd3f-11e7-86e5-0307c95fc99c.png)

@lingyielia @xd515 

This is the what it looks like when the python script runs. It will capture all the requests and the query that you pass:

![image](https://user-images.githubusercontent.com/31963299/35175064-f1eb8706-fd3f-11e7-8e11-43ce0fc39fd2.png)

**Comment by vr00n** [comment]
AWESOME work @gauravcusp 

Curious does this handle spatial querying like : 
`https://varun-cusp2.carto.com/api/v2/sql?q=SELECT%20*%20FROM%20master_crosswalk_nad83%20where%20ST_Contains(the_geom,%20ST_GeomFromText(%27POINT(-73.952686%2040.775745)%27,4326))`
?

Lets add this to tomorrow's meeting.

**Comment by gauravcusp** [comment]
@vr00n 
The crosswalk documents didn't have geography column attached so the query won't work. Also since I didn't connect the script with a database, query won't return any result. I stored the json file on AWS and extracted data using the link. If needed, I can work on script that uses database instead of a json file directly.

**Comment by gauravcusp** [comment]
Hi @vr00n 
I've prepared the diagram for API [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/API/API.jpg). Please go through it and let me know if my understanding is correct.
@lingyielia @xd515

**Comment by vr00n** [comment]
Great work @gauravcusp. Few comments:

1. Number the arrows to create a sequence of actions
2. How does the Lambda "populate" the database? The data, once created, stays in the DB. This is just a simple select query right?

![image](https://user-images.githubusercontent.com/4397663/35257895-3c222188-ffb9-11e7-8e56-665357fc6f0c.png)

**Comment by gauravcusp** [comment]
@vr00n 
What i was thinking was using the switch statement for every city we use. If the user location is in NY, the script would extract the data from our NY file and create a table with that data. Query would be performed after that on the populated data (something like CREATE TABLE  IF NOT EXISTS ABC).

Another approach could be, prepoluate data while setting up database and then.perform select queries on them based on the location.

I hope I'm not lacking in the understanding of the workflow. I'll number the arrows but basically the process starts with UI and ends there as well.

**Comment by vr00n** [comment]
Noted. For the time being, lets keep it simple.  

Load the LA + NYC data to PostGres as 2 separate tables.
```
If:
User queries a location from NYC - then select from NYC table 
elseif :
User queries a location from LA - then select from LA table 
```

**Comment by gauravcusp** [comment]
Updated 

![image](https://user-images.githubusercontent.com/31963299/35285375-3516b7d8-002b-11e8-985b-84991d564d4a.png)

**Comment by patwater** [comment]
This looks super cool! Are you all able to present on Friday?

**Comment by gauravcusp** [comment]
Hey @patwater do you mean present the API on Friday? Because we're still in early stages of its development.

**Comment by lingyielia** [comment]
LA data loaded on the AWS RDS now. [Here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/API/LoadGISdataIntoAWS_RDS.md) shows how we did it.

**Comment by patwater** [comment]
@gauravcusp idea with Friday is just a 10 minute informal presentation to show progress. So could talk about what's involved with generating a geo-cross-walk, the data you integrated and the API could be a final bit about what's to come

**Comment by gauravcusp** [comment]
@patwater sure we can do that. Let us know about the meeting on Friday (time and schedule).

**Comment by patwater** [comment]
10 AM to noon PST = 1 PM -3 PM EST. Did you get the cal invite?

**Comment by lingyielia** [comment]
@patwater , I haven't received the call invite.

**Comment by patwater** [comment]
Could you please send me an email?  I'll add you to the cal invite

**Comment by gauravcusp** [comment]
I got one for Saturday's meeting. I hope that's what you're talking about.

**Comment by lingyielia** [comment]
@patwater , mine is lz1714@nyu.edu

**Comment by patwater** [comment]
@gauravcusp it's Friday not Saturday. There's a separate Saturday workshop on dash as a data viz tool

**Comment by gauravcusp** [comment]
@patwater In that case, please send me the invite too. My id is bhardwaj@nyu.edu

**Comment by lingyielia** [comment]
@vr00n @gauravcusp @xd515  @patwater
Guys, check this out! [A simple LA County Geocrosswalk App](https://calm-stream-52725.herokuapp.com/)

**Comment by gauravcusp** [comment]
Additional Note: We have hosted the app on heroku since there were some complications with AWS.

**Comment by gauravcusp** [comment]
@vr00n Can we have the shapefile for NYC as well? We can incorporate that with our code and make it public.

**Comment by vr00n** [comment]
@gauravcusp uploaded zipped shapefile
https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/NYC_master_crosswalk_nad83.zip

**Comment by vr00n** [comment]
@lingyielia Tested and verified looking AWESOME!!!

https://calm-stream-52725.herokuapp.com/results?lonSearch=-118.520259&latSearch=34.215713

**Comment by gauravcusp** [comment]
I asked some of my friends for their feedback and I think they can be incorporated in the future. I'll create another issue for that and we can probably work on it sometime in future.

**Comment by lingyielia** [comment]
@vr00n @gauravcusp Cool! I will update the README soon.

**Comment by vr00n** [comment]
Thanks @gauravcusp - Can you please update the README with heroku deployment step-by-step instructions please ?

Thanks!

**Comment by lingyielia** [comment]
@vr00n 
[This readme](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/APP/README.md) explained how I build this app. If anything is not clear please let me know.

**Comment by lingyielia** [comment]
APP deployed [here](https://calm-stream-52725.herokuapp.com/), doc [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/APP/README.md).
