### ISSUE TITLE
County Level geographies vs City geographies

### ISSUE THREAD

**Issue by gauravcusp** [argo-marketplace/LA-LocalGeo-CrossWalk#12]
After our merge with all the geographies, we realized that a lot of county level data is going un-utilized as intersection with city-level geographies end up in giving the results at city level. In order to preserve the data of other cities in the county, we propose to merge just county level shapefiles and create a separate csv for them (some of the geographies are at city level currently will not be considered). 

@vr00n please let us know if we should go ahead with this proposal.

@lingyielia @xd515 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
Hmm. I am skeptical because the purpose of this project is to create a single file. 

Can you provide a more concrete example for `a lot of county level data is going un-utilized as intersection with city-level geographies end up in giving the results at city level`?

Why not `union` all the city-level shapefiles into 1 shapefile and then intersect it with LA county.

In NYC case, boroughs = LA cities and all data was provided for all boroughs.

In this case, we will need to clean the data such that all the datasets we need to intersect contain all LA cities in the same file.

Consider School Districts, i dont think you can just use LA city's school districts shapefile, you will need to union School District for **all cities** in LA county and only then can you intersect.

**Comment by gauravcusp** [comment]
@vr00n @lingyielia @xd515 

For instance we have school districts at county level and in the resultant file we are left with just the school district in LA city. (which you already mentioned in your post)
![image](https://user-images.githubusercontent.com/31963299/34655496-c7ae1898-f3d8-11e7-888d-6f42c83b64ee.png)

From my understanding of 1st week's discussion, I was under the impression that we have to intersect all the geometries and get the results for the smallest intersecting geometry.

We can consider individual cities and take their union but there are 88 cities in LA county and not all of them have proper shapefiles for all the geographies. 

For now, we can try using union for all our geographies and see the quality of data we end up with. Let us know if that makes sense.

**Comment by vr00n** [comment]
Ok so lets state the challenge here more clearly:

We have a good inventory of LA County geographies.
We **do not** have a good inventory of local geographies for all the cities in LA County.

I think the confusion here was that we confused LA County and LA City. Apologies if that was not made clear earlier. 

Please review this to clarify the **difference between LA COUNTY and City of LA**
https://www.quora.com/Why-is-Los-Angeles-made-up-of-88-cities

The Inventory that we have created so far can be further improved -
 https://docs.google.com/spreadsheets/d/1knENEZA57BtFOr489FJA3yA8folo-5lYsNi-qiRsR74/edit#gid=0

Lets try to spend some time on this inventory and clearly specify which shapefiles are county level and which ones are city level with the goal of answering which of the following exist at COUNTY level:

- City boundaries
- Census Blocks 2010
- Census Tracts 2010
- City Council Districts
- Community Districts
- County Supervisorial Seats
- Fire stations
- Health Area
- Municipal Court Districts
- Neighborhood Tabulation Areas
- Police Precincts
- PUMA
- Retail Water Districts
- School Districts
- State Assembly Districts
- State Senate Districts
- U.S. Congressional Districts
- Wholesale water districts (member agencies of Metropolitan Water District)

**Comment by gauravcusp** [comment]
@vr00n we've updated the [file](https://docs.google.com/spreadsheets/d/1knENEZA57BtFOr489FJA3yA8folo-5lYsNi-qiRsR74/edit#gid=0) with county and city classification.

**Comment by lingyielia** [comment]
Working on the county level as discussed.
