### ISSUE TITLE
Compare results of geopandas with Arcgis

### ISSUE THREAD

**Issue by lingyielia** [argo-marketplace/LA-LocalGeo-CrossWalk#13]
Perform the overlay task on Arcgis with the same data we used [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/Week2/Week2_deliverable.ipynb) to double check our result.

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by lingyielia** [comment]
<img width="522" alt="screen shot 2018-01-07 at 3 42 53 pm" src="https://user-images.githubusercontent.com/31973683/34653923-d89c24b8-f3c1-11e7-867a-636a09571d13.png">

The result of `spatial_overlay` is not exactly the same as the result generated from Arcgis. I found some similar concerns regarding [doing overlay on large datasets](https://stackoverflow.com/questions/42474847/geopandas-overlay-intersection).

Do you think this difference is acceptable?

**Comment by vr00n** [comment]
Thanks @lingyielia - please prepare to demonstrate this on our next meeting.

**Comment by lingyielia** [comment]
__Compare the performance of__ `spatial_overlay`, `qgis`, __and__ `arcgis`
- Algorithm:  `spatial_overlay` = `qgis` ≠ `arcgis`
- Speed: `arcgis` > `spatial_overlay` = `qgis`
- How they deal with 'invalid geometries': `arcgis` (handled somehow by itself), `spatial_overlay` (set a buffer of 0 to make the geometries valid), `qgis` (throw error)

For more information, see the discussion at the end of [here](https://github.com/geopandas/geopandas/pull/429#issuecomment-356479727).

**Comment by vr00n** [comment]
Closed because this is beyond scope of this particular project but something that we need to look at in the future

**Comment by lingyielia** [comment]
@vr00n , These are [Data with Invalid Geometries](https://github.com/lingyielia/Ops/blob/master/DataWithInvalidGeometries.ipynb). If you need any further information, please let me know.

**Comment by patwater** [comment]
Hi team any objections to closing this issue? Doing some housekeeping
