### ISSUE TITLE
Steps on ArcGIS

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#14]
@lingyielia  please document the steps for intersecting the County level geographies in Arcgis. This will be helpful reference for future iterations.

Please produce file titled `arcgis-intersections.csv` that contain this result?

Thank you!

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?
#

**Comment by lingyielia** [comment]
@vr00n @gauravcusp @xd515 
Please find the document for intersecting the County level geographies in ArcGIS [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/CreateGeocrosswalkbyArcgis.md) and the [arcgis-intersections.csv](https://drive.google.com/file/d/1yaRMp1azgGNlv1EKMMUXXEALfReRfz_7/view?usp=sharing)

I will close this issue now.
