### ISSUE TITLE
Team Meeting- Jan13

### ISSUE THREAD

**Issue by lingyielia** [argo-marketplace/LA-LocalGeo-CrossWalk#15]
Colleagues @vr00n @xd515 @gauravcusp

## Meeting discussion
- Keep county level geometries only.
- Progress on API.
- Performance differences using `Arcgis`, `QGIS`, `spatial_overlays`, `sjoin`.

## Issues for this week
- Next Saturday for AWS Workshop.
- Document ArcGIS process and generate the final CSV.
- Polish the notebook doing the intersecting with geopandas.
- Explore the API (optional)

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by patwater** [comment]
Minor knit... FYI this geocrosswalk csv requires permission: https://drive.google.com/drive/u/0/folders/1S2W_ffWTB8f-mwz96WH0E45KUPERU7HZ

Any reason this couldn't be open?

**Comment by lingyielia** [comment]
Hi @patwater ,
I just updated the csv file. Here is the link of our final version geocrosswalk csv:
https://drive.google.com/file/d/1yaRMp1azgGNlv1EKMMUXXEALfReRfz_7/view?usp=sharing

This csv is too large to be rendered on google drive. You might need download it to see the content.

**Comment by gauravcusp** [comment]
Hey @vr00n , do we have a call tomorrow?
@lingyielia @xd515

**Comment by vr00n** [comment]
Sure - lets. 
Can you please create a new issue for Jan 21 meeting + agenda - lets do meet.google and 11 AM EST. please send cal as well?

Thanks @gauravcusp

**Comment by gauravcusp** [comment]
@vr00n For my id, meet.google provides option to join a call but not create one. I guess its a paid service for businesses.

**Comment by gauravcusp** [comment]
- Document ArcGIS process and generate the final CSV.
-- [Documentation](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/14)
- Polish the notebook doing the intersecting with geopandas.
-- [Notebook](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/The%20intersection%20utilized%20GeoPandas.ipynb)
- Explore the API (optional)
-- [Redirecting to discussion](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/10)
