### ISSUE TITLE
Team Meeting - 01/21

### ISSUE THREAD

**Issue by gauravcusp** [argo-marketplace/LA-LocalGeo-CrossWalk#16]
## Objective for tomorrow's call

- Review the final results
- Review API results

@vr00n  @lingyielia  @xd515 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by lingyielia** [comment]
## Issues for this week
- Test invalid geometries using Qgis
- Polish the repo
- Goal: API for LA County and New York
