### ISSUE TITLE
IDEA: this would be a great resource for LACounts.org !

### ISSUE THREAD

**Issue by dmarulli** [argo-marketplace/LA-LocalGeo-CrossWalk#17]
If you're interested in sharing your results, would be great to write up a short blog post illustrating how you developed this geo-cross-walk and how it would be useful for the LA open data community

CC @patwater @gauravcusp

**Comment by gauravcusp** [comment]
Thanks @dmarulli! We'd definitely get the blog started as soon as we're done with the publicly accessible API.

**Comment by lingyielia** [comment]
@xd515 @gauravcusp 
I opened the BlogDraft doc [here](https://docs.google.com/document/d/1JHmhscg0wrKXIaN5qcbuRKV6uDXKJVbrvEmCzKUlO-Y/edit), please feel free to edit and comment!

**Comment by gauravcusp** [comment]
Hey @vr00n @patwater , we've drafted a version of our blog post and would really appreciate your feedback. 
Here's the link to the doc: [blogpost](https://docs.google.com/document/d/1JHmhscg0wrKXIaN5qcbuRKV6uDXKJVbrvEmCzKUlO-Y/edit#)

@lingyielia @xd515

**Comment by patwater** [comment]
@gauravcusp @lingyielia could you please add patrick@argolabs.org as a collaborator to the blog post? Also I added a few edits. Post is getting close! Looking forward to sharing with the world :)

**Comment by gauravcusp** [comment]
Thanks @patwater . I just added you as a collaborator to the blog post. I'll add updated screenshots to the post.
