### ISSUE TITLE
Conduct Kickoff meeting

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#2]
- Discuss project with registered contributors. 
- Answer any questions. 
- Review [dirt simple project spec.](https://github.com/argo-marketplace/test-project/blob/master/README.md)
- Assign the following roles:

`SCRIBE:` During a project, this `SOLVER` role will be responsible for maintaining project notes, minutes and ensuring documentation is up to date. This role will need to be filled during Project Kickoff meeting and can be revolved every so often.

`OPS`: During a project, this `SOLVER` role will be responsible for ensuring schedules and that the team is able to communicate without issue. The person under this role will organize meetings/conference-calls/hangouts as necessary. This role will need to be filled during Project Kickoff meeting and can be revolved every so often.

**Comment by vr00n** [comment]
Hi there @iuk0162 @lingyielia @xd515 @gauravcusp

Great call yesterday and apologies for showing up late. 

As discussed, we will start slowly + simply. I have created 2 issues for the following:

1. How many **local geographies** do we have for Los Angeles based on [links we have?](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk#how-will-we-get-this-done). Are these the same local geos as NYC local geographies from https://github.com/vr00n/NYC-LocalGeo-CrossWalk?

2. Collaboratively Create a simple ipython notebook to intersect 2 polygons with different attributes to output single polygon with "intersected attributes". We will discuss the creation of this file next week.

Lastly, since you are  4, please team up and nominate yourselves for `SCRIBE` and `OPS` roles and lets plan to schedule a 1 hour call next Saturday/Sunday to discuss progress.

I will close this issue once the nominations are complete and calendar invite is sent out by `OPS`

Thanks!

**Comment by gauravcusp** [comment]
@vr00n 
Here's the link to the spreadsheet consisting shapefile mapping of both the cities.

https://drive.google.com/open?id=1knENEZA57BtFOr489FJA3yA8folo-5lYsNi-qiRsR74

Lets us know if there are some changes that need to be made. @lingyielia @xd515 

Additionally, @lingyielia will be taking over SCRIBE role while I'll be taking the OPS role
