### ISSUE TITLE
API Stack choice

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#22]
Hi @gauravcusp - I noticed in https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/APP/README.md that the stack to stand up the API is as follows
These are self explanatory:
- Amazon RDS
- PostgresSQL
- PostGIS
- git

...but can you please update what these do or what they control in a few short sentences?

- Node.js
- npm
- Express
- EJS
- pg-promise
- bluebird
- Heroku CLI

While this is very cool, Im looking to simplify this stack and figure out how we can do the same using `AWS Lambda` and `API Gateway` with a simple HOW TO QUERY THIS API page.

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by gauravcusp** [comment]
@vr00n sure I'll update it soon!

**Comment by patwater** [comment]
Very cool and very excited for this API!

**Comment by vr00n** [comment]
@gauravcusp check out https://geosearch.planninglabs.nyc/ for some pointers as well.

**Comment by lingyielia** [comment]
@vr00n , Thank you for this great reference! This website gives us a very clear idea of how would our final website be like.

**Comment by gauravcusp** [comment]
@vr00n I keep following this guy because he makes things so easy for NYC open data users. The map and reverse-geocoding is what we're planning next, so the user would be able to drop a pin and enter some address manually to get the data.

**Comment by lingyielia** [comment]
@vr00n @gauravcusp @patwater , 
Good news, An API is deployed using AWS api-gateway and lambda.
[Here is an example](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/AWS_API_Gateway/API_user_instruction.ipynb) of using this api. I will write the deploy process soon.

**Comment by lingyielia** [comment]
[Deploy process](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/AWS_API_Gateway/README.md)

**Comment by vr00n** [comment]
@lingyielia this is super amazing! WOW! I am really very impressed with the level of documentation. THANK YOU! This should totally make it to a blog post!

**Comment by lingyielia** [comment]
Thank you, @vr00n ! Many references you shared with us are very helpful! Gaurav and I are preparing for the blog post now.

**Comment by patwater** [comment]
Very cool! Maybe I'm slow and missing something though is the API live somewhere? Curious to poke around

**Comment by gauravcusp** [comment]
Hey @patwater 
Here are the APIs for NYC and LA

https://d5tgnm602g.execute-api.us-east-1.amazonaws.com/beta/nyc?long=-73.987493&lati=40.693258

 https://d5tgnm602g.execute-api.us-east-1.amazonaws.com/beta/la?long=-118.408518&lati=33.945421

Its not on the UI yet, but you can play around by changing the coordinates.

**Comment by patwater** [comment]
Ah beautiful. In an ideal world the UI would include a link to the API along with some documentation. This API user guide is really great though could benefit from a concrete analysis example using the geo-cross-walk: https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/AWS_API_Gateway/API_user_instruction.ipynb

**Comment by lingyielia** [comment]
@patwater 
You are right, we will definitely update our UI with API related features

**Comment by lingyielia** [comment]
@vr00n @patwater @gauravcusp ,
New version is here https://geocrosswalk.herokuapp.com/. Any suggestion on the content of the api page?

**Comment by patwater** [comment]
Looking very good! One quick question: the api page loads pretty slowly? Is that because it's running on a free / small heroku page?

**Comment by lingyielia** [comment]
@patwater ,
Yes, I believe that's the reason. As we are using a free plan on Heroku, which will sleep after minutes inactive. To restart it might take some time.
btw, I added [a nyc 311 data example of using our geo-cross-walk](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/AWS_API_Gateway/API_user_instruction.ipynb) at the end of this notebook.

**Comment by patwater** [comment]
Very cool! When you get a chance please dive back into the blog post and finish that up so we can help showcase your great work :)

**Comment by gauravcusp** [comment]
Thanks @patwater! we've started updating the blog document and it should be ready soon.

**Comment by patwater** [comment]
Cool please ping and pass along the gdoc when ready for me to review 👍
