### ISSUE TITLE
Compare LA and NYC geographies

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#3]
Understand local geographies.

How many local geographies do we have for Los Angeles based on links we have?

Are these the same local geographies as NYC local geographies from https://github.com/vr00n/NYC-LocalGeo-CrossWalk?

Expecting a simple inventory of all the geographies for LA COUNTY similar to https://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page

**Comment by gauravcusp** [comment]
Hi @vr00n , 

Do we just map the NYC boundaries with LA or add any other boundary that didn't exist for NY? Also, since LA doesn't have boroughs, we can use districts or counties in place of it, right?

**Comment by vr00n** [comment]
@gauravcusp 
A simple comparison will do. So maybe you all can create a Google Spreadsheet and list the NYC local geographies and the _equivalent_ LA county geographies side-by-side.

Do both have School Districts?

>Also, since LA doesn't have boroughs, we can use districts or counties in place of it, right?

Right!

**Comment by gauravcusp** [comment]
@vr00n 

Yes, both of the cities have school districts. I've prepared the spreadsheet and will share it with you after discussion with the team.

**Comment by vr00n** [comment]
Great! Once you have a link you can share, please post here.

**Comment by vr00n** [comment]
oops accidentally closed it :)

**Comment by vr00n** [comment]
@vr00n
Here's the link to the spreadsheet consisting shapefile mapping of both the cities.

https://drive.google.com/open?id=1knENEZA57BtFOr489FJA3yA8folo-5lYsNi-qiRsR74

**Comment by vr00n** [comment]
@gauravcusp can you please update the README with this link. Its getting hard to find in a closed issue. Thanks!

**Comment by gauravcusp** [comment]
Added to README!
