### ISSUE TITLE
Super simple ipython notebook to intersect using geopandas.

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#4]
Super simple ipython notebook to intersect 2 polygons with different attributes to output single polygon with "intersected attributes". 

You can experiment with whatever you like - maybe even pick 2 local geographies from Los Angeles.

We will discuss this IPython Notebook next week. 

Please ensure your notebook is executable and readable.

**Comment by gauravcusp** [comment]
@vr00n 
I've added the notebook to this repo. We've used 2 sets of geographies to perform spatial intersection.

**Comment by vr00n** [comment]
😲 This is epic @gauravcusp ! Great progress. Especially this part where you were able to isolate a specific area and demonstrate the intersection. Please share this progress with the the team!

![image](https://user-images.githubusercontent.com/4397663/34369811-56005270-ea7c-11e7-9087-006e9169cbc9.png)

Next steps are to repeat this process for all geographies and produce a master-intersection attribute file that contains attributes from all the geographies.

Stretch Goal is to build an API functionality on top of the master intersection file.

I guess we can either close this or  #6 as they seem similar? @xd515 

Keep it up. Please collaborate and share wins

1 team 1 dream.

**Comment by gauravcusp** [comment]
Hey @vr00n .

When you did the geo cross-walk for NYC, what method did you use? Spatial join or spatial overlay? Because the geopandas overlay function takes forever to run on big files such as census blocks or tracks.

**Comment by vr00n** [comment]
I actually used the Intersect function in QGIS.

via https://docs.qgis.org/2.18/en/docs/user_manual/processing/vector_menu.html#geoprocessing-tools

![image](https://user-images.githubusercontent.com/4397663/34426341-827d0736-ebf2-11e7-937c-c2d86c23a0a3.png)

You may need to research or ask in stackoverflow what the corresponding geopandas function is.

Spatial Overlay _sounds_ right...

**Comment by vr00n** [comment]
@gauravcusp - please provide resolution details before closing the issue. In this case, where is the `Super simple ipython notebook` located? Thank You!

**Comment by gauravcusp** [comment]
Please visit the notebook [here](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/blob/master/Week2/Week2_deliverable.ipynb).
