### ISSUE TITLE
A result of the intersection

### ISSUE THREAD

**Issue by xd515** [argo-marketplace/LA-LocalGeo-CrossWalk#6]
Hi @vr00n, I made a super simple intersection of census tracts and census blocks utilizing sjoin. 
Here are the questions:
1. The shape of intersected shapefile, as I consumed that it should have the same number of rows as that of census blocks, had more rows than the sum of rows of tracts and blocks.
2. When we make intersections of multiple polygons in the future, should we obey the order by beginning from the lower levels such as blocks to the higher levels such as communities?

**Comment by vr00n** [comment]
Hi @xd515 . ❤️ Super Simple  :)

1. The correct number of rows should match the smallest geography. In this is case, the resultant intersection operation should have the same number of rows as `blocks` as they are smaller than tracts.

2. Yes, now that we have Local geography file - https://docs.google.com/spreadsheets/d/1knENEZA57BtFOr489FJA3yA8folo-5lYsNi-qiRsR74/edit#gid=0 - the next step is to order them by number of rows and then intersecting them one by one starting from the smallest (blocks) to the largest polygons.

3. I have a feeling that even by not following an order, you will still get a good result. Can you test this in a super simple manner with 3-4 geographies? Maybe post your results here with/screenshots to confirm?

Tx!

**Comment by vr00n** [comment]
@xd515 - please provide a note on why we are closing this before closing an issue. Thank you.

**Comment by xd515** [comment]
This issue is on the same topic as #4, so we could close it.
