### ISSUE TITLE
Team meeting - Dec 30

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/LA-LocalGeo-CrossWalk#7]
@gauravcusp  (OPS), Please send a brief agenda for the meeting tomorrow. What do we review?
@lingyielia (SCRIBE) - please prepare to update this issue with the meeting notes during our call. 

Thanks and looking forward to talking tomorrow.

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by gauravcusp** [comment]
@vr00n @lingyielia @xd515 @iuk0162 

PFB agenda for tomorrow’s meeting:
 
- We’ll be going through the spreadsheet created this week to see if any geography is to be added/removed

- We’ll have a screen-share walkthrough of the notebook we created this week for intersection of some of the geographies of LA city

- We’ll have discussion of what needs to be improved in the current methodology

- Discussion of next week’s tasks

**Comment by lingyielia** [comment]
Colleagues @vr00n @iuk0162 @xd515 @gauravcusp

We've made progress!

## Issues for this week
1. Create a single CSV file intersecting all geometries.
- Add in more geometries in the spreadsheet.
- How many geometries do we end up with?
- Find which method is equivalent to the method in QGIS.

2. Create an API (Stretching goals)
- Upload CSV to Carto, exporting as API
- More resources to explore:
AWS workshop, [dirt-simple-postgis-http-api](https://github.com/tobinbradley/dirt-simple-postgis-http-api)

Happy New Year!

**Comment by gauravcusp** [comment]
@vr00n @lingyielia @xd515 

Issues handled this week:

- Create a [spreadsheet](https://drive.google.com/open?id=1W-fXFVE4afhv26R_GSmod-XU4AsJdtm5) of all the geometries
- Find which method is equivalent to the method in QGIS: 
  - The results from QGIS are similar to that of spatial overlay

- API tasks will be taken up in Week 3
